### ISSUE TITLE
Users without admin permissions cant access the bot

### ISSUE THREAD

**Issue by realSZ27** [manuel-rw/jellyfin-discord-music-bot#181] opened 2023-05-13 05:21 UTC
**Describe the bug**
Non-admins can't access slash commands.

**To Reproduce**
1. Set up bot.
2. View server as a role without admin.
3. Try a command (/play)

**Expected behavior**
It would allow you to use the slash commands and play music.

**Screenshots**
User can't access the bot
![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/99378252/d9bbf2ad-ba57-4d78-97b5-001ac0380d6a)

**Additional context**
All back end is working, jellyfin and the bot are all working fine.

**Comment by manuel-rw** [comment] 2023-05-13 06:54
Duplicate of #119

**Closed by manuel-rw** 2023-05-13 06:54 UTC
