### ISSUE TITLE
Bot crashes from any input

### ISSUE THREAD

**Issue by krevoit** [manuel-rw/jellyfin-discord-music-bot#64] opened 2023-01-21 08:35 UTC
**Describe the bug**
After running and installing all the dependencies, the bot gives an error and crashes. This is both with the docker install, as well as the yarn install.

```[Nest] 2006280  - 01/21/2023, 7:26:04 PM   DEBUG [JellyfinWebSocketService] Opening WebSocket with client id jellyfin-discord-bot...
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 404
    at ClientRequest.<anonymous> (/root/jellyfin-discord-music-bot/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/root/jellyfin-discord-music-bot/node_modules/ws/lib/websocket.js:1004:13)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.```

**Comment by manuel-rw** [comment] 2023-01-21 13:53
Hi, thank you for your issue.
Sadly, the error does not tell me much where it could have originated from.
I will try a few things and try to reproduce.

**Comment by manuel-rw** [comment] 2023-01-21 14:02
I wasn't able to reproduce your exact error.
I assume that it has most likely to do something with your configuration and the jellyfin server address, since we use websockets for communication.
But in my case, I got a proper message when the address is invalid:
```
[Nest] 6208  - 21/01/2023, 15:00:45   ERROR [JellyfinService] AxiosError: Request failed with status code 404
```

**Comment by krevoit** [comment] 2023-01-22 14:11
Thanks for the quick response. I did try again directly connecting to the server ip and port (without a reverse proxy). I am using the source right now. For input, any command I use, such as play or summon causes the bot to crash.

From the logs, it looks like it is connecting to Jellyfin properly. A similar error occurs once searching to /play a song when a result returns.

This is a log with /summon
```[Nest] 2400989  - 01/23/2023, 1:05:00 AM   DEBUG [JellyfinService] Created Jellyfin Client and Api
[Nest] 2400989  - 01/23/2023, 1:05:00 AM     LOG [PlayItemCommand] Subscribe to event(on): interactionCreate
(node:2400989) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 interactionCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
[Nest] 2400989  - 01/23/2023, 1:05:05 AM   DEBUG [JellyfinService] Connected using user 'x'
[Nest] 2400989  - 01/23/2023, 1:05:05 AM   DEBUG [JellyinPlaystateService] Reported playback capabilities sucessfully
[Nest] 2400989  - 01/23/2023, 1:05:07 AM     LOG [NestApplication] Nest application successfully started +2138ms
[Nest] 2400989  - 01/23/2023, 1:05:19 AM   DEBUG [JellyfinWebSocketService] Opening WebSocket with client id jellyfin-discord-bot...
node:events:368
      throw er; // Unhandled 'error' event
      ^

DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/root/jellyfin-discord-music-bot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/root/jellyfin-discord-music-bot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/root/jellyfin-discord-music-bot/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async ChatInputCommandInteraction.reply (/root/jellyfin-discord-music-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:251:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: [
          {
            color: 7828684,
            author: [Object],
            footer: [Object],
            description: "I'm ready to play media. Use ``Cast to device`` in Jellyfin or the ``/play`` command to get started."
          }
        ],
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',```

**Comment by krevoit** [comment] 2023-01-22 14:21
Additionally, sometimes the search works, but on selecting a song the bot does not play music and Discord shows 'This interaction failed'. It does join the voice channel however.

```[Nest] 2404064  - 01/23/2023, 1:18:29 AM   DEBUG [JellyfinSearchService] Searching for 'slasher'
[Nest] 2404064  - 01/23/2023, 1:18:29 AM   DEBUG [JellyfinSearchService] Found 1 results for 'slasher'
[Nest] 2404064  - 01/23/2023, 1:18:38 AM   DEBUG [JellyfinWebSocketService] Opening WebSocket with client id jellyfin-discord-bot...
[Nest] 2404064  - 01/23/2023, 1:18:40 AM   DEBUG [JellyfinWebSocketService] Received a ForceKeepAlive package from the server
[Nest] 2404064  - 01/23/2023, 1:18:45 AM     LOG [RegisterCommandService] All global commands are registered!
[Nest] 2404064  - 01/23/2023, 1:18:51 AM   DEBUG [DiscordVoiceService] Avoided joining the voice channel because voice connection is already defined
[Nest] 2404064  - 01/23/2023, 1:19:00 AM   DEBUG [JellyfinWebSocketService] Sent a KeepAlive package to the server
[Nest] 2404064  - 01/23/2023, 1:19:00 AM   DEBUG [JellyfinWebSocketService] Received a KeepAlive package from the server
[Nest] 2404064  - 01/23/2023, 1:19:01 AM   DEBUG [DiscordVoiceService] Avoided joining the voice channel because voice connection is already defined
[Nest] 2404064  - 01/23/2023, 1:19:21 AM   DEBUG [DiscordVoiceService] Avoided joining the voice channel because voice connection is already defined
[Nest] 2404064  - 01/23/2023, 1:19:30 AM   DEBUG [JellyfinWebSocketService] Sent a KeepAlive package to the server
[Nest] 2404064  - 01/23/2023, 1:19:30 AM   DEBUG [JellyfinWebSocketService] Received a KeepAlive package from the server```

**Comment by manuel-rw** [comment] 2023-01-22 14:28
> A similar error occurs once searching to /play a song when a result returns.

Looks like the interaction is timing out before the reply is being sent.
On which device are you the bot running on? Is it maybe a low power device or an older CPU?

Solution might be to defer the reply before doing any asynchronous work: https://stackoverflow.com/questions/67413046/slash-commands-unknown-interaction/68774492#68774492

> Additionally, sometimes the search works, but on selecting a song the bot does not play music and Discord shows 'This interaction failed'. It does join the voice channel however.

Could be caused by the same issue as above.

> I am using the source right now. For input, any command I use, such as play or summon causes the bot to crash.

Does this mean, that using the internal IP, bypassing the proxy, fixed your initial error?

**Comment by manuel-rw** [comment] 2023-01-22 20:56
I made a quick refactor in 066d27b, so all interactions use the asynchronous API and the proper defer update API.
This way, Discord will know that the requests has been retrieved by the bot, and will not be timed out, unless it exceeds 5 minutes (I believe it's 5).
This is especially useful, if a command takes more than 3 seconds to complete and potentially solves your issue.
Can you run from source and check if the error doesn't happen anymore?

**Comment by krevoit** [comment] 2023-01-23 06:54
I don't think changing the jellyfin link did anything. Its a pretty modern device on an i7 CPU (ubuntu 20.04)

I've compiled again from source and looks like the same issue unfortunately.
When playing a song with /play and selecting the track, the bot joins the voice call, but doesn't play anything.
In discord it shows `Applying your selection to the queue...
This may take a moment. Please wait` , and the log is the same as above https://github.com/manuel-rw/jellyfin-discord-music-bot/issues/64#issuecomment-1399502263.

Tried /summon again and it crashed showing this log (May be the same as https://github.com/manuel-rw/jellyfin-discord-music-bot/issues/64#issuecomment-1399499144)
```[Nest] 2621595  - 01/23/2023, 5:47:46 PM   DEBUG [JellyfinService] Created Jellyfin Client and Api
[Nest] 2621595  - 01/23/2023, 5:47:46 PM     LOG [PlayItemCommand] Subscribe to event(on): interactionCreate
(node:2621595) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 interactionCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
[Nest] 2621595  - 01/23/2023, 5:47:47 PM   DEBUG [JellyfinService] Connected using user 'ea103d64b8594276bd88af9276b36e89'
[Nest] 2621595  - 01/23/2023, 5:47:47 PM   DEBUG [JellyinPlaystateService] Reported playback capabilities sucessfully
[Nest] 2621595  - 01/23/2023, 5:47:54 PM     LOG [NestApplication] Nest application successfully started +6417ms
node:events:368
      throw er; // Unhandled 'error' event
      ^

DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/root/jellyfin-discord-music-bot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/root/jellyfin-discord-music-bot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/root/jellyfin-discord-music-bot/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async ChatInputCommandInteraction.reply (/root/jellyfin-discord-music-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async SummonCommand.handler (/root/jellyfin-discord-music-bot/dist/commands/summon.command.js:41:9)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:251:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: [ { color: 7828684, author: [Object], footer: [Object] } ],
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/callback'
}
error Command failed with exit code 1.```

**Comment by manuel-rw** [comment] 2023-01-23 07:47
I found this issue:
https://github.com/discordjs/discord.js/issues/7005

Looks like it's a known problem. First step is now the defer, so a timeout shouldn't be the issue here.
What are your steps when running the bot?
Maybe try starting in production mode if you haven't tried that.

**Comment by manuel-rw** [comment] 2023-01-24 12:47
Is the error still the same?

**Comment by krevoit** [comment] 2023-01-24 12:48
yes

**Comment by manuel-rw** [comment] 2023-01-24 12:50
Has your bot sufficient permissions? I didn't implement any warnings yet, and don't know how the bot will react, if the permissions are insufficient.

**Comment by manuel-rw** [comment] 2023-01-24 12:51
You confirmed that the error still is the same.
If that's true, here's where it fails:
https://github.com/manuel-rw/jellyfin-discord-music-bot/blob/320fb2d15372c56610f7be186e843d1a2c2b9d6e/src/commands/summon.command.ts#L40

I forgot to await this, but I highly doubt that this is the cause.
The bot only calls this method, if it was unable to join or open the voice channel.
Permissions could be a reason for thus.

**Comment by manuel-rw** [comment] 2023-01-24 21:01
I looked into this a bit further. Do you run multiple bots on the same token?
According to some posts, that is not feasible, especially if they set the activity.
If not, you could try regenerating the token.

**Comment by manuel-rw** [comment] 2023-01-24 21:05
Related issues:
https://github.com/discordjs/discord.js/issues/7005
https://github.com/discord/discord-api-docs/issues/5558

**Comment by krevoit** [comment] 2023-01-28 12:41
Bot has all permissions enabled, its just this single app on this bot, and I regenerated the token as well.

**Comment by 7kayoh** [comment] 2023-02-04 17:58
Late to this issue but I have mentioned something similar while I was working on a pull request for the stop command, this kind of error didn't really occur much back then but the pull request seems to have intensified it.

Not sure what the actual cause is, but could be something I edited, maybe the service file [src/clients/jellyfin/jellyfin.playstate.service.ts](https://github.com/manuel-rw/jellyfin-discord-music-bot/blob/master/src/clients/jellyfin/jellyfin.playstate.service.ts) as most solutions of this error seem to be related to `await`

**Comment by 7kayoh** [comment] 2023-02-04 17:59
Though, my working change isn't merged into the master branch so I might have overlooked

**Comment by manuel-rw** [comment] 2023-02-04 18:03
> Late to this issue but I have mentioned something similar while I was working on a pull request for the stop command, this kind of error didn't really occur much back then but the pull request seems to have intensified it.
> 
> Not sure what the actual cause is, but could be something I edited, maybe the service file [src/clients/jellyfin/jellyfin.playstate.service.ts](https://github.com/manuel-rw/jellyfin-discord-music-bot/blob/master/src/clients/jellyfin/jellyfin.playstate.service.ts) as most solutions of this error seem to be related to `await`

Thanks for the info. The issue is, that I simply cannot replicate this issue on my system.
The linked sources also indicate that this issue is probably related to the Discord API (eg. inappropriate usage or rate limiting).
Not using an await can produce such errors, but I doubt that this is the actual cause here.

> Though, my working change isn't merged into the master branch so I might have overlooked

Sorry, that I didn't merge this yet. I want to make a few more changes before releasing a new version.
I'll consider creating the release soon.

**Comment by manuel-rw** [comment] 2023-02-19 21:32
Does this still happen on the latest ``dev`` version?
I now automatically create development images. Simply change from the ``latest`` image to ``dev``.
There might be a few other bugs on ``dev``, but this one might has been resolved, as I made a ton of updates of dependencies.

**Comment by manuel-rw** [comment] 2023-03-14 22:34
@krevoit

**Comment by akowa-ss** [comment] 2023-03-18 04:40
Like hardly crashes now, so far I have only seen one error with the message "Unknown interaction"

```
[Nest] 28  - 03/17/2023, 4:12:39 PM   ERROR [ExceptionsHandler] Unknown interaction
DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:933:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/app/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async AutocompleteInteraction.respond (/app/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
    at async PlayItemCommand.onAutocomplete (/app/dist/commands/play/play.comands.js:134:9)
    at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
    at async /app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

**Comment by manuel-rw** [comment] 2023-03-26 12:07
I belive that this is just an upstream issue of the Discord API / library.
Best thing we can probably do is, to frequently update dependencies to keep up with Discord's API updates.

**Comment by h1ght** [comment] 2023-03-28 09:52
> 

ive struggled with this kind of, im using it in docker compose/portainer. ive setted the timezone for my place and now it works.

**Comment by manuel-rw** [comment] 2023-03-28 09:55
@krevoit can you try this? Perhaps setting the timezone will resolve your issue.

**Comment by krevoit** [comment] 2023-03-28 10:25
> @krevoit can you try this? Perhaps setting the timezone will resolve your issue.

Will do in the next hour or so and see if there is any change. I am running from source however.

**Comment by manuel-rw** [comment] 2023-03-28 14:16
Are there any errors when it doesn't play music?

Can you attach / send the log when you run the dev version?

**Comment by h1ght** [comment] 2023-03-28 15:14
> well I tried the source, it looks like its actually working but only thing is that it doesn't play audio.
> 
> The docker i tried doesn't connect to Jellyfin for some reason, the dev version on Docker times out connecting to the server >also after 5 mins then crashes.

how u run the docker image? are u connecting via lan/homesetup
does the docker log give you kind of http code? like 401, 404?
`version: "3.7"

services:
 manuel-rw:
    ports:
      - '3000:3000'
    environment:
      - DISCORD_CLIENT_TOKEN=xxxx
      - JELLYFIN_SERVER_ADDRESS=http://192.168.178.42:8096
      - JELLYFIN_AUTHENTICATION_USERNAME=xxx
      - JELLYFIN_AUTHENTICATION_PASSWORD=xx
      - TZ=Europe/Berlin
    image: 'ghcr.io/manuel-rw/jellyfin-discord-music-bot:latest'`

**Comment by ArchemedIan** [comment] 2023-04-06 23:29
i had an issue with the bot crashing/not connecting and portainer logs indicated something about <somehost:443> timing out. (without debug logs)

 i immediately recreated the container with DNS set (1.1.1.1, 1.0.0.1) havent had an issue with the bot not connecting or crashing since

i think sometimes docker drops DNS for some reason, interrupting the bots connection to discord. specifying DNS has also solved issues in other containers for me

dont know if this is the solution but it felt worth mentioning

**Comment by manuel-rw** [comment] 2023-04-07 10:06
Thank you for the detailed information, @ArchemedIan .
Can the others here check, if those instructions change the behavior?

**Comment by krevoit** [comment] 2023-04-10 07:35
The docker-compose still doesn't work, the bot gets stuck on thinking after issuing a command, and the songs don't show up as I am searching them. nothing relevant in the logs either.

Also tried grabbing the lastest source and compiling and I get this error on yarn build:
```
src/commands/play/play.comands.ts:159:42 - error TS2345: Argument of type 'string | SearchType | undefined' is not assignable to parameter of type 'SearchType | undefined'.
  Type 'string' is not assignable to type 'SearchType | undefined'.

159       PlayCommandParams.getBaseItemKinds(type),
                                             ~~~~

Found 1 error(s).

error Command failed with exit code 1.
```

I feel its just my machine messing up, I'm going to spin up another remote server and see if i get the same issues

**Comment by manuel-rw** [comment] 2023-04-10 07:42
Can you do ``git checkout dev`` and try again to build?

**Comment by krevoit** [comment] 2023-04-10 07:43
> git checkout dev

Already on 'dev'
Your branch is up to date with 'origin/dev'.

**Comment by manuel-rw** [comment] 2023-04-10 08:36
Fixed it. You can re-try

**Comment by Lurk390** [comment] 2023-05-07 23:11
I am also experiencing a very similar issue; got the exact same stack trace except my error code is 302 after `/summon` or `/play`. I am using docker compose and have tried setting timezone and DNS, but the issue still persists. I should note that it seems like the bot connects to the server fine, as the autocomplete while searching using discord commands works and shows my music.

Here is my `compose.yaml` file:
```
jellyfin-discord-music-bot:
    container_name: jellyfin-discord-music-bot
    image: ghcr.io/manuel-rw/jellyfin-discord-music-bot:dev
    restart: unless-stopped
    environment:
      - TZ=America/Detroit
      - DISCORD_CLIENT_TOKEN=$JELLYFIN_CLIENT_TOKEN
      - JELLYFIN_SERVER_ADDRESS=http://192.168.88.101:8096/jellyfin
      - JELLYFIN_AUTHENTICATION_USERNAME=$JELLYFIN_AUTHENTICATION_USERNAME
      - JELLYFIN_AUTHENTICATION_PASSWORD=$JELLYFIN_AUTHENTICATION_PASSWORD
    ports:
      - 3000:3000
    dns:
      - 1.1.1.1
      - 1.0.0.1
```

**Comment by manuel-rw** [comment] 2023-05-08 05:34
Hi, does your base name really end with /jellyfin?
Can you maybe try to remove that suffix?

**Comment by manuel-rw** [comment] 2023-05-08 15:55
Ok. Status code 302 means, that there is a temporary redirection. Perhaps you should use the direct URL instead?

**Comment by Lurk390** [comment] 2023-05-08 17:32
What do you mean by direct URL? When I tried removing the base URL (so it's  just `192.168.88.101:8096`), I got the error I mentioned previously.

Is there support for base URLs or do you think it is just a problem with my configuration?

**Comment by manuel-rw** [comment] 2023-05-08 17:50
Is Jellyfin running at ``192.168.88.101`` on ``8096`` or is that your proxy?
In theory, it should just work fine if that is Jellyfin itself.

Also, have you tried the above suggestions (timezone, DNS, ...)?

**Comment by Lurk390** [comment] 2023-05-08 18:00
`192.168.88.101:8096` should be Jellyfin itself. The reverse proxy connects to my domain name so I can access it outside my network, which I connect using `<mydomain>.dev/jellyfin`.

I have also tried both the timezone and DNS suggestions with no luck.

**Closed** 2023-11-19 14:18 UTC
Labels: bug, help wanted, discord
